In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import random as rd


#échauffement

a = np.array([1,2,3])
#print(a[:,None])
#print(a[None, :])
#print(a[:, None] - a[None, :])

b = np.array([[1,2,3],[1,2,3]])
print(b)
print(b[:, None,:])
print(b[:,:,None])
print(b[:, None,:] - b[:,:,None])


[[1 2 3]
 [1 2 3]]
[[[1 2 3]]

 [[1 2 3]]]
[[[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]]
[[[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]

 [[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]]


In [46]:
# initialisation aléatoire
# les bornes pour le tirage au sort initial

mass_max = 3.    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.
speed_max = 1.

def init_problem(N):
    masses = np.random.uniform(0.1,mass_max,N)
    positions = np.random.uniform(np.array([[x_min],[x_max]]),np.array([[y_min],[y_max]]),(2,N))
    speeds = np.random.uniform(np.array([[0],[1]]),np.array([[0],[1]]),(2,N))
    return masses,positions,speeds

print(init_problem(4))
#test de init_problem

masses, positions, speeds = init_problem(10)

try:
    assert masses.shape == (10,) and positions.shape == speeds.shape == (2, 10)
    print("OK")
except:
    print("KO")

(array([0.26175864, 2.40732365, 2.8733094 , 1.55242527]), array([[-10., -10., -10., -10.],
       [ 10.,  10.,  10.,  10.]]), array([[0., 0., 0., 0.],
       [1., 1., 1., 1.]]))
OK


In [53]:
#fonction commode donnée

def init3():
    # first element is sun-like: heavy, at the center, and no speed
    masses = np.array([3, 1, 1], dtype=float)
    positions = np.array([
        [0, 5, -5], 
        [0, 1, -1]], dtype=float)
    speeds = np.array([
        [0, -1, 1], 
        [0, 0, 0]], dtype=float)
    return masses, positions, speeds

masses, positions, speeds = init3()


In [ ]:
#Les forces

def forces(masses, positions, G=1.0):
    diff = positions[:,:, None] - positions[:,None,:]
    distance = np.linalg.norm(diff,axis = 0)
    np.fill_diagonal(distance,1)
    coeff = G*/distance
    return diff,distance
print(forces(masses,positions,1))

(array([[[  0.,  -5.,   5.],
        [  5.,   0.,  10.],
        [ -5., -10.,   0.]],

       [[  0.,  -1.,   1.],
        [  1.,   0.,   2.],
        [ -1.,  -2.,   0.]]]), array([[ 0.        ,  5.09901951,  5.09901951],
       [ 5.09901951,  0.        , 10.19803903],
       [ 5.09901951, 10.19803903,  0.        ]]))
